config/routes.rb
Rails.application.routes.draw do
  post '/decks/:id/manage', to: 'decks#manage', as: 'deck_manage'
  get '/decks/:id/scope', to: 'decks#scope', as: 'deck_scope'
  resources :decks do
  end

  root to: 'static#index'
  get 'about' => 'static#about'
  get 'contact' => 'static#contact'

  get 'user/:username', to: 'user#show', as: 'user_show'

  devise_for :users
  devise_scope :user do
      get 'users/sign_out' => 'devise/sessions#destroy'
  end

  resource 'card' do
      root to: 'card#list', as: 'index'
      get 'show/:slug', to: 'card#show', as: ''
      get 'search', to: 'card#search', as: 'search'
  end

  get 'config/show/:format', to: 'card#show_format', as: 'card_format'

end

app/models/card.rb
class Card < ActiveRecord::Base
    enum ctype: [:creature, :evolution, :spell]
    has_and_belongs_to_many :abilities
    has_and_belongs_to_many :races
    has_and_belongs_to_many :civs
    has_many :printings
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  class QueryParser
    attr :query, :parts
    CivMap = {
      'l' => 'Light',
      'w' => 'Water',
      'd' => 'Darkness',
      'f' => 'Fire',
      'n' => 'Nature'
    }

    def initialize query
      @query = Card.order('name')
      @parts = query.downcase.gsub(/"(\w+) (\w+)"/, '"\1☃\2"').split.each do |part|
        part.gsub!(/"(\w+)☃(\w+)"/, '\1 \2')
      end
    end
    def parse
      @parts.each do |part|
        if part.match(/.+[!:].+/)
          if part[':']
            part = part.split ':'
            case part.first
            when "set"
              set part
            when "race"
              race part
            when "civ"
              civ part
            end
          else
            part = part.split '!'
            case part.first
            when "civ"
              civ! part
            end
          end
        elsif part.match(/[<>=!]/)
          part = /(.+)([<>=]{1,2})(.+)/.match(part)
          case part[1]
          when 'rarity'
            rarity part
          when 'cost', 'power'
            @query = @query.where("#{part[1]} #{part[2]} ?", Integer(part[3]))
          end
        else
          @query = @query.where('cards.name ILIKE ?', "%"+part+"%")
        end
      end
      self
    end
    private
    def set part
      @query = @query
      .joins(:printings)
      .joins(:printings => :cardset)
      .where("cardsets.name ILIKE ? OR cardsets.short ILIKE ?", "%#{part.last}%", "%#{part.last}%")
    end
    def rarity part
      @query = @query
      .joins(:printings)
      .where("printings.rarity #{part[2]} ?", Integer(part[3]))
    end
    def race part
      @query = @query
      .joins(:races)
      .where('races.name ILIKE ?', "%#{part.last}%")
    end
    def civ! part
      return civmulti!(part) if part.last.match(/[mM]$/)
      parts = {}
      part.last.gsub(/[mM]/, '').split('').map do |civshort|
        parts[civshort] = CivMap[civshort]
      end
      parts = (CivMap.values - parts.values).map do |v|
        Civ.find_by_name v
      end
      @query = @query
      .where('cards.id NOT IN (select card_id from cards_civs WHERE civ_id IN (?))', parts)

      #@query = @query.joins(:civs)
      #.group('cards_civs.card_id')
      #.having('cards_civs.civ_id NOT IN (?)', parts)
    end
    def civmulti! part
      parts = {}
      part.last.gsub(/[mM]/, '').split('').map do |civshort|
        parts[civshort] = CivMap[civshort]
      end
      @query = @query.where('cards.id IN (SELECT card_id FROM cards_civs WHERE civ_id NOT IN (?) GROUP BY card_id HAVING count(card_id) > 1)', (CivMap.values - parts.values).map do |v|
        Civ.find_by_name v
      end)
    end
    def civ part
      @query = @query.joins(:civs)
      .where('civs.id IN (?)', part.last.gsub(/[mM]/, '').split('').map do |civshort|
        Civ.find_by_name CivMap[civshort]
      end)
      civmulti if part.last.match(/[mM]$/)
    end
    def civmulti
      @query = @query.where('cards.id IN (SELECT card_id FROM cards_civs GROUP BY card_id HAVING count(card_id) > 1)')
      #@query = @query.group('cards_civs.card_id').having('count(cards_civs.card_id) > 1')
    end
  end
  def list
    @cards = Card.all
  end
  def show
    @card = Card.find_by_slug params[:slug]
  end
  def search
    @querystring = params[:q]
    @queryobject = QueryParser.new params[:q]
    @cards = @queryobject.parse.query
  end
  def show_format
    session[:card_show_format] = params[:format]

    redirect_back_or_default
  end
end

app/helpers/card_helper.rb
module CardHelper
  def current_deck_card_count number, card
    out = {
      class: 'btn btn-default'
    }
    found = false
    current_deck.deck_cards.each do |deck_card|
      if deck_card.card_id == card.id
        found = true
        if deck_card.amount == number
          out = {
            class: 'btn btn-primary',
            disabled: 'disabled'
          }
        end
      end
    end
    if !found and number == 0
      out = {
        class: 'btn btn-primary',
        disabled: 'disabled'
      }
    end
    out
  end
end

app/views/card/_show.html.erb
<div class="row card">
    <div class="col-xs-12 col-md-4">
        <% if card.printings.length > 0 %>
            <% if search %>
                <%= link_to image_tag(card.printings.first.art), card_path(slug: card.slug) %>
            <% else %>
                <%= image_tag(card.printings.first.art) %>
            <% end %>
        <% end %>
    </div>
    <div class="col-xs-12 col-md-8">
        <table cellspacing="0" class="table table-striped">
            <tbody>
                <tr>
                    <th class="col-sm-3">Name</th>
                    <td class="col-sm-9">
                        <% if search %>
                            <%= link_to card.name, card_path(slug: card.slug) %>
                        <% else %>
                            <%= card.name %>
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-3">Civilizations</th>
                    <td class="col-sm-9">
                        <ul>
                        <% card.civs.each do |civ| %>
                            <li><%= civ.name %></li>
                        <% end %>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-3">Cost</th>
                    <td class="col-sm-9"><%= card.cost %></td>
                </tr>
                <tr>
                    <th class="col-sm-3">Type</th>
                    <td class="col-sm-9"><%= card.ctype.capitalize %></td>
                </tr>
                <% if card.ctype == 'creature' %>
                <tr>
                    <th class="col-sm-3">Races</th>
                    <td class="col-sm-9">
                        <ul>
                            <% card.races.each do |race| %>
                                <li><%= race.name %></li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-3">Power</th>
                    <td class="col-sm-9"><%= card.power %></td>
                </tr>
                <% end %>
                <tr>
                    <th class="col-sm-3">Abilities</th>
                    <td class="col-sm-9">
                        <ul>
                            <% card.abilities.each do |ability| %>
                                <li>
                                <strong><%= ability.name %></strong>
                                <%= ability.reminder %>
                                <% if ability.text %>
                                    &mdash;
                                    <span><%= ability.text %></span>
                                <% end %>
                                </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-3">Printings</th>
                    <td class="col-sm-9">
                        <ul>
                            <% card.printings.each do |printing| %>
                                <li>
                                <strong>
                                    <%= printing.cardset.name %>
                                    (<% printing.rarity.times do %>
                                        *
                                     <% end %>)
                                </strong>
                                &mdash;
                                <span><%= printing.number %></span>
                                </li>
                            <% end %>
                        </ul>
                    </td>
                </tr>
                <% if is_managing_deck? %>
                <tr>
                    <th class="col-sm-3">Current Deck</th>
                    <td class="col-sm-9">
                        <%= form_tag(deck_manage_path(id: current_deck.id)) do |f| %>
                            <%= hidden_field_tag('card_id', card.id) %>
                            <div class="btn-group">
                                <%= submit_tag("0",  current_deck_card_count(0, card)) %>
                                <%= submit_tag("1",  current_deck_card_count(1, card)) %>
                                <%= submit_tag("2",  current_deck_card_count(2, card)) %>
                                <%= submit_tag("3",  current_deck_card_count(3, card)) %>
                            </div>
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/card/index.html.erb
<h1>Cards</h1>
<ul>
    <% @cards.each do |card| %>
        <li><%= card.name %></li>
    <% end %>
</ul>

app/views/card/list.html.erb
<h1>Cards</h1>
<ul>
    <% @cards.each do |card| %>
        <li><%= card.name %></li>
    <% end %>
</ul>

app/views/card/search.html.erb
<% if Rails.env == 'development' %>
    <div class="panel">
        <div class="panel-heading">
            <div class="h3">Development Information</div>
        </div>
        <div class="panel-body">
            <pre>
<%= @queryobject.query.to_sql %>
            </pre>
        </div>
    </div>
<% end %>
<%= render partial: "cards_#{current_card_format}_list.html.erb", locals: {cards: @cards, search: true} %>

app/views/card/show.html.erb
<h1><%= @card.name %></h1>
<%= render partial: 'card_show.html.erb', locals: {card: @card, search: false} %>