config/routes.rb
Rails.application.routes.draw do
  post '/decks/:id/manage', to: 'decks#manage', as: 'deck_manage'
  get '/decks/:id/scope', to: 'decks#scope', as: 'deck_scope'
  resources :decks do
  end

  root to: 'static#index'
  get 'about' => 'static#about'
  get 'contact' => 'static#contact'

  get 'user/:username', to: 'user#show', as: 'user_show'

  devise_for :users
  devise_scope :user do
      get 'users/sign_out' => 'devise/sessions#destroy'
  end

  resource 'card' do
      root to: 'card#list', as: 'index'
      get 'show/:slug', to: 'card#show', as: ''
      get 'search', to: 'card#search', as: 'search'
  end

  get 'config/show/:format', to: 'card#show_format', as: 'card_format'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :deck_cards
  belongs_to :user
  enum format: {
    open: 'open',
    standard: 'standard'
  }
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :manage]
  before_action :check_ownership, only: [:edit, :update, :destroy, :manage]
  before_action :check_visibility, only: [:edit, :update, :destroy, :show, :manage]

  # GET /decks
  # GET /decks.json
  def index
    if user_signed_in?
      @decks = Deck.where('active = true').where('public = true OR user_id = ?', current_user.id)
    else
      @decks = Deck.where('active = true').where('public = true')
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user
    @deck.active = true

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        puts @deck.inspect
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end

  # GET /decks/1/scope
  # GET /decks/1/scope.json
  def scope
    session[:current_deck] = params[:id]
    session[:current_deck] = nil if params[:id] == '0'
    respond_to do |format|
      format.html { redirect_back_or_default }
      format.json { head :no_content }
    end
  end

  #POST /decks/1/manage
  #POST /decks/1/manage.json
  def manage
    @card = Card.find(params[:card_id])
    @deck_card = DeckCard.where('deck_id = ?', @deck.id).where('card_id = ?', params[:card_id]).first

    if !@deck_card
      @deck_card = DeckCard.new deck: @deck,
        card: @card
    end
    @deck_card.amount = params[:commit]
    @deck_card.save

    respond_to do |format|
      format.html { redirect_back_or_default }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name, :description, :public, :format)
    end

    # Only allow modifications by the owner of the deck
    def check_ownership
      if current_user != @deck.user
        redirect_to root_path, notice: 'You cannot edit someone else\'s deck!'
      end
    end

    def check_visibility
      if !@deck.active or (current_user != @deck.user and !@deck.public)
        not_found
      end
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.select :format, options_for_select(
        Deck.formats,
        @deck.format
    ), include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Public</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= deck.description %></td>
        <td><%= deck.public %></td>
        <td><%= deck.active %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p>
    <%= link_to 'Edit', edit_deck_path(@deck) %> |
    <%= link_to 'Back', decks_path %>
</p>
<div class="row">
    <strong class="col-xs-2">Name:</strong>
    <p class="col-xs-10">
        <%= @deck.name %>
    </p>
</div>
<div class="row">
    <strong class="col-xs-2">Description:</strong>
    <p class="col-xs-10">
        <%= @deck.description %>
    </p>
</div>
<div class="row">
    <strong class="col-xs-2">Public:</strong>
    <p class="col-xs-10">
        <%= @deck.public %>
    </p>
</div>
<% @deck.deck_cards.each do |deck_card| %>
    <% if deck_card.amount > 0 %>
        <%= render partial: 'card_show.html.erb', locals: {card: deck_card.card, search: true} %>
    <% end %>
<% end %>