config/routes.rb
Rails.application.routes.draw do
  post '/decks/:id/manage', to: 'decks#manage', as: 'deck_manage'
  get '/decks/:id/scope', to: 'decks#scope', as: 'deck_scope'
  resources :decks do
  end

  root to: 'static#index'
  get 'about' => 'static#about'
  get 'contact' => 'static#contact'

  get 'user/:username', to: 'user#show', as: 'user_show'

  devise_for :users
  devise_scope :user do
      get 'users/sign_out' => 'devise/sessions#destroy'
  end

  resource 'card' do
      root to: 'card#list', as: 'index'
      get 'show/:slug', to: 'card#show', as: ''
      get 'search', to: 'card#search', as: 'search'
  end

  get 'config/show/:format', to: 'card#show_format', as: 'card_format'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kaijudo DB</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'bootstrap.min.css', media: 'all' %>
<%= stylesheet_link_tag    'styles.css', media: 'all' %>
<%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Kaijudo DB</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li<% if current_page?(root_path) %> class="active"<% end %>>
                        <%= link_to 'Home', root_path %>
                    </li>
                    <li<% if current_page?(about_path) %> class="active"<% end %>>
                        <%= link_to 'About', about_path %>
                    </li>
                    <li<% if current_page?(contact_path) %> class="active"<% end %>>
                        <%= link_to 'Contact', contact_path %>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Decks <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= decks_path %>">Browse Decks</a></li>
                            <% if user_signed_in? %>
                            <li><a href="">My Decks</a></li>
                            <li><a href="<%= new_deck_path %>">Create New Deck</a></li>
                            <% end %>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left navbar-collapse collapse" role="search" action="<%= search_card_path %>" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" placeholder="Search"<% if params[:q] %> value="<%= params[:q] %>"<% end %>>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right navbar-collapse collapse">
                    <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <%= image_tag(gravatar_url(current_user.email, s:25)) %>
                            Account
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="<%= destroy_user_session_path %>">Sign Out</a></li>
                        </ul>
                    </li>
                    <% else %>
                    <li><a href="<%= new_user_session_path %>">Sign In</a></li>
                    <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
                    <% end %>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>

        <div class="push"></div>
    </div> <!-- /container -->
    <div id="footer" class="navbar navbar-default navbar-fixed-bottom" role="navigation">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a data-toggle="dropdown" href="#" class="dropdown-toggle">Card View Mode <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to_card_format 'Spolier', 'spoiler' %>
                            </li>
                            <li>
                                <%= link_to_card_format 'List', 'list' %>
                            </li>
                            <li>
                                <%= link_to_card_format 'Scans only', 'image' %>
                            </li>
                            <li>
                                <%= link_to_card_format 'Cards with Scans', 'image_text' %>
                            </li>
                        </ul>
                    </li>
                    <% if user_signed_in? %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Deck Management <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <% Deck.formats.each do |format| %>
                                    <li class="dropdown-header">
                                        <%= format.first %>
                                    </li>
                                    <% current_user.decks.each do |deck| %>
                                        <% if deck.format == format.last %>
                                            <li><%= link_to deck.name, deck_scope_path(id: deck.id) %></li>
                                        <% end %>
                                    <% end %>
                                    <li class="divider"></li>
                                <% end %>
                                <li><%= link_to "Cancel Management", deck_scope_path(id: 0) %></li>
                            </ul>
                        </li>
                    <% end %>
                </ul>
                <% if user_signed_in? %>
                    <p class="nav navbar-text">
                        <% if is_managing_deck? %>
                            Currently managing: <%= current_deck.name %>
                        <% else %>
                            Not currently managing any deck.
                        <% end %>
                    </p>
                <% end %>
                <p class="nav navbar-right navbar-text">&copy; 2014 Stephen Middleton</p>
            </div>
        </div>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
</body>
</html>